/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_NhanVien;
import DTO.NhanVien;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author ADMIN
 */
public class FrameNhanVien extends javax.swing.JPanel {

    BLL_NhanVien nv = new BLL_NhanVien();
    /**
     * Creates new form FrameNhanVien
     */
    public FrameNhanVien() {
        initComponents();
        hienThi();
        
    }
    public void hienThi()
    {
        DefaultTableModel model = (DefaultTableModel) jTbNV.getModel();

        
        ArrayList<NhanVien> list = new ArrayList<NhanVien>();
        list = nv.getArrayList();
    
        model.setRowCount(0);
        for(int i = 0 ; i < list.size();i++)
        {
            
//            System.out.println(list.get(i).isTinhTrang());
            model.addRow(new Object[]{list.get(i).getMaNV(),list.get(i).getTen(),list.get(i).getNgSinh(),list.get(i).getDiaChi(),list.get(i).getSdt()} );
        }
    }
    public void hienThi(ArrayList<NhanVien> list)
    {
        DefaultTableModel model = (DefaultTableModel) jTbNV.getModel();

        
        
        model.setRowCount(0);
        for(int i = 0 ; i < list.size();i++)
        {
            
//            System.out.println(list.get(i).isTinhTrang());
            model.addRow(new Object[]{list.get(i).getMaNV(),list.get(i).getTen(),list.get(i).getNgSinh(),list.get(i).getDiaChi(),list.get(i).getSdt()} );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbNV = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jrbMa = new javax.swing.JRadioButton();
        jrbTen = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(850, 600));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý nhân viên");

        jTbNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Tên NV", "Ngày Sinh", "Địa chỉ", "Số điện thoại"
            }
        ));
        jTbNV.setRowHeight(30);
        jTbNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbNVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTbNV);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/them bt 50x50.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtSearch.setToolTipText("Tìm kiếm");
        txtSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearchCaretUpdate(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Tìm Kiếm");

        buttonGroup1.add(jrbMa);
        jrbMa.setSelected(true);
        jrbMa.setText("Mã NV");

        buttonGroup1.add(jrbTen);
        jrbTen.setText("Tên NV");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh bt 50x50.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jrbMa)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbTen))
                                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(203, 203, 203)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbMa)
                    .addComponent(jrbTen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrameAddNV iNV = new FrameAddNV();
        iNV.setVisible(true);
        iNV.setResizable(false);
        iNV.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTbNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbNVMouseClicked
        // TODO add your handling code here:
        int i=jTbNV.getSelectedRow();
        FrameThongTinNhanVien f = new FrameThongTinNhanVien();
        if(i>=0)
        {

            try {
                DefaultTableModel model = (DefaultTableModel) jTbNV.getModel();
                f.txtMaNV.setText(model.getValueAt(i, 0).toString());
                FrameAddAccount.maNV_tmp = model.getValueAt(i, 0).toString();
                f.txtMaNV.setEditable(false);
                f.txtTenNV.setText(model.getValueAt(i, 1).toString());
                Date date1 = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(i, 2).toString());
                f.txtDate.setDate(date1);
                f.txtDiaChi.setText(model.getValueAt(i, 3).toString());
                f.txtSDT.setText(model.getValueAt(i, 4).toString());
                f.setVisible(true);
                f.setLocationRelativeTo(null);
                f.setResizable(false);
            } catch (ParseException ex) {
                Logger.getLogger(FrameNhanVien.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
    }//GEN-LAST:event_jTbNVMouseClicked

    private void txtSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearchCaretUpdate
        
        if(jrbMa.isSelected())
        {
            hienThi(nv.timKiemTheoMa(txtSearch.getText()));
        }
        else
        {
            hienThi(nv.timKiem(txtSearch.getText()));
        }
        
    }//GEN-LAST:event_txtSearchCaretUpdate

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        hienThi();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbNV;
    private javax.swing.JRadioButton jrbMa;
    private javax.swing.JRadioButton jrbTen;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
