/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_NCC;
import BLL.BLL_NSX;
import DTO.NhaCungCap;
import DTO.NhaSanXuat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class FrameDoiTac extends javax.swing.JPanel {

    BLL_NCC bll_ncc = new BLL_NCC();
    BLL_NSX bll_nsx = new BLL_NSX();
    /**
     * Creates new form FrameDoiTac
     */
    public FrameDoiTac() {
        initComponents();
        hienthiNCC();
        
    }

    public void hienthiNCC()
    {
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        
        ArrayList<NhaCungCap> list = new ArrayList<NhaCungCap>();
        list = bll_ncc.getArrayList();
        model.setColumnCount(0);
        model.addColumn("Mã NCC");
        model.addColumn("tên NCC");
        model.addColumn("Địa chỉ");
        model.addColumn("Số điện thoại");
        model.setRowCount(0);
        for(int i = 0 ; i < list.size();i++)
        {
            

            model.addRow(new Object[]{list.get(i).getMaNCC(),list.get(i).getTenNCC(),list.get(i).getDiaChi(),list.get(i).getSdt()} );
        }
    }
    public void hienthiNCC(ArrayList<NhaCungCap> list)
    {
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        
         
        
        model.setColumnCount(0);
        model.addColumn("Mã NCC");
        model.addColumn("tên NCC");
        model.addColumn("Địa chỉ");
        model.addColumn("Số điện thoại");
        model.setRowCount(0);
        for(int i = 0 ; i < list.size();i++)
        {
            

            model.addRow(new Object[]{list.get(i).getMaNCC(),list.get(i).getTenNCC(),list.get(i).getDiaChi(),list.get(i).getSdt()} );
        }
    }
    public void hienthiNSX()
    {
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        
        ArrayList<NhaSanXuat> list = new ArrayList<NhaSanXuat>();
        list = bll_nsx.getArrayList();
        model.setColumnCount(0);
        model.addColumn("Mã NSX");
        model.addColumn("tên NSX");
        model.addColumn("Quốc gia");
        
        model.setRowCount(0);
        for(int i = 0 ; i < list.size();i++)
        {
            
            model.addRow(new Object[]{list.get(i).getMaNSX(),list.get(i).getTenNSX(),list.get(i).getQuocGia()} );
        }
    }
    public void hienthiNSX(ArrayList<NhaSanXuat> list)
    {
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        
        
        model.setColumnCount(0);
        model.addColumn("Mã NSX");
        model.addColumn("tên NSX");
        model.addColumn("Quốc gia");
        
        model.setRowCount(0);
        for(int i = 0 ; i < list.size();i++)
        {
            
            model.addRow(new Object[]{list.get(i).getMaNSX(),list.get(i).getTenNSX(),list.get(i).getQuocGia()} );
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jrbMa = new javax.swing.JRadioButton();
        jrbTen = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Thông tin đối tác");

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhà Cung Cấp", "Nhà Sản Xuất" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/them bt 50x50.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Tìm Kiếm");

        txtTimKiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTimKiemCaretUpdate(evt);
            }
        });

        buttonGroup1.add(jrbMa);
        jrbMa.setSelected(true);
        jrbMa.setText("Mã");

        buttonGroup1.add(jrbTen);
        jrbTen.setText("Tên");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh bt 50x50.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jrbMa)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbTen))
                                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 343, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbMa)
                            .addComponent(jrbTen)))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        if(jComboBox1.getSelectedItem().equals("Nhà Cung Cấp"))
        {
            hienthiNCC();
        }
        else
        {
            hienthiNSX();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i=jTable1.getSelectedRow();
        
        if(jComboBox1.getSelectedItem().equals("Nhà Cung Cấp"))
        {
            if(i>=0)
            {
               FrameThongTinNCC fNCC = new FrameThongTinNCC();
               DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
               fNCC.txtMaNCC.setText(model.getValueAt(i, 0).toString());
               fNCC.txtMaNCC.setEditable(false);
               fNCC.txtTenNCC.setText(model.getValueAt(i, 1).toString());
               fNCC.txtDiaChi.setText(model.getValueAt(i, 2).toString());
               fNCC.txtSDT.setText(model.getValueAt(i, 3).toString());               
               fNCC.setVisible(true);
               fNCC.setLocationRelativeTo(null);
               fNCC.setResizable(false);

            }
        }
        else 
        {
            FrameThongTinNSX fNSX = new FrameThongTinNSX();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            fNSX.txtMaNSX.setText(model.getValueAt(i, 0).toString());
            fNSX.txtMaNSX.setEditable(false);
            fNSX.txtTenNSX.setText(model.getValueAt(i, 1).toString());
            fNSX.txtQuocGia.setText(model.getValueAt(i, 2).toString());         
            fNSX.setVisible(true);
            fNSX.setLocationRelativeTo(null);
            fNSX.setResizable(false);
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().equals("Nhà Cung Cấp"))
        {
            FrameAddNCC iNV = new FrameAddNCC();
            iNV.setVisible(true);
            iNV.setResizable(false);
            iNV.setLocationRelativeTo(null);
        }
        else
        {
            FrameAddNSX iNV = new FrameAddNSX();
            iNV.setVisible(true);
            iNV.setResizable(false);
            iNV.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTimKiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTimKiemCaretUpdate
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().equals("Nhà Cung Cấp"))
        {
            if(jrbMa.isSelected())
            {
                hienthiNCC(bll_ncc.timKiemTheoMa(txtTimKiem.getText()));
            }
            else
            {
                hienthiNCC(bll_ncc.timKiemTheoTen(txtTimKiem.getText()));
            }
        }
        else
        {
            if(jrbMa.isSelected())
            {
                hienthiNSX(bll_nsx.timKiemTheoMa(txtTimKiem.getText()));
            }
            else
            {
                hienthiNSX(bll_nsx.timKiemTheoten(txtTimKiem.getText()));
            }
        }
    }//GEN-LAST:event_txtTimKiemCaretUpdate

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().equals("Nhà Cung Cấp"))
        {
            hienthiNCC();
        }
        else
        {
            hienthiNSX();
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton jrbMa;
    private javax.swing.JRadioButton jrbTen;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
