/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_CtPhieuXuat;
import BLL.BLL_KhachHang;
import BLL.BLL_NhanVien;
import BLL.BLL_PhieuXuat;
import BLL.BLL_ThietBi;

import DTO.CtPhieuXuat;
import DTO.KhachHang;
import DTO.NhaCungCap;
import DTO.NhaSanXuat;
import DTO.NhanVien;
import DTO.PhieuNhap;
import DTO.PhieuXuat;
import DTO.ThietBi;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ad
 */
public class FrameAddPhieuXuat extends javax.swing.JFrame {
 BLL_PhieuXuat PX = new BLL_PhieuXuat();
 BLL_CtPhieuXuat ctPX = new BLL_CtPhieuXuat();
 BLL_KhachHang KH = new BLL_KhachHang();
 BLL_ThietBi TB = new BLL_ThietBi();
 BLL_NhanVien NV = new BLL_NhanVien();
    /**
     * Creates new form FrameAddPhieuXuat
     */
    public FrameAddPhieuXuat() {
      setTitle("Thêm Phiếu Xuất");
       ArrayList<KhachHang> list = KH.getArrayList();
       ArrayList<ThietBi> listTB = TB.getArrayList();     
       
       initComponents();
       donGiatext.setEditable(false);
        for(int i=0 ; i<list.size();i++)
        {
            maKHtext.addItem(list.get(i).getMaKH()+"-"+list.get(i).getTen());
            String maKH = (String) maKHtext.getSelectedItem();
            String maKHcut =maKH.substring(0,maKH.indexOf("-"));
            if(maKHcut.equals(list.get(i).getMaKH()))
            {
             maKHtxt.setText(list.get(i).getMaKH());
            }
            
        }
        
         for(int i=0 ; i<listTB.size();i++)
        {
            maTBtext.addItem(listTB.get(i).getMaTB()+"-"+listTB.get(i).getTenTB());
            String maTB = (String) maKHtext.getSelectedItem();
            String maTBcut =maTB.substring(0,maTB.indexOf("-"));
             if(maTBcut.equals(listTB.get(i).getMaTB()))
             {
               donGiatext.setText(Integer.toString(listTB.get(i).getGiaThanh()));
               maTBx.setText(listTB.get(i).getTenTB());
             }
        }         
         
       
        hienThiTable();
      
        
        
    }
  
     public void hienThiTable()
    {
        
        DefaultTableModel model = (DefaultTableModel) bangPX.getModel();

        
        ArrayList<PhieuXuat> list = new ArrayList<PhieuXuat>();
        list = PX.getArrayList();
        
        model.setRowCount(0);
        for(int i = 0 ; i < list.size();i++)
        {
            
            model.addRow(new Object[]{list.get(i).getMaPX(),list.get(i).getNgayMua(),list.get(i).getMaNV(),list.get(i).getMaKH()} );
        }
        
    }
     public void hienThiTableCT(String maPX)
    {
        
        DefaultTableModel model = (DefaultTableModel) bangCtPX.getModel();

        
        ArrayList<CtPhieuXuat> list = new ArrayList<CtPhieuXuat>();
        list = ctPX.getArrayList();
        
        model.setRowCount(0);
        for(int i = 0 ; i < list.size();i++)
        {
             if(maPX.equals(list.get(i).getMaPX()))
            model.addRow(new Object[]{list.get(i).getMaTB(),list.get(i).getDonGia(),list.get(i).getSoLuong()} );
        }
        
    }
    public void xacNhan(String maPX)
    {
        if(PX.timTinhTrang(maPX).equals("true"))
        {
            jbtThanhToan.setEnabled(false);
        }
        else jbtThanhToan.setEnabled(true);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NgayLaptext = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        maKHtext = new javax.swing.JComboBox<>();
        ThongBao = new javax.swing.JLabel();
        mapxj = new javax.swing.JLabel();
        maPXtext = new javax.swing.JLabel();
        MaNVtext = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        maNVtxt = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangPX = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        donGiatext = new javax.swing.JTextField();
        soLuongtext = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bangCtPX = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        maTBtext = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        matbangian = new javax.swing.JLabel();
        soluongcu = new javax.swing.JLabel();
        jlbhinh = new javax.swing.JLabel();
        maKHtxt = new javax.swing.JLabel();
        maTBx = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jbtThanhToan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Phiếu xuất");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Phiếu Xuất", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel1.setText("Mã PX");

        jLabel2.setText("Ngày Mua");

        NgayLaptext.setEnabled(false);

        jLabel3.setText("Tên NV");

        jLabel5.setText("Mã KH");

        maKHtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maKHtextActionPerformed(evt);
            }
        });

        ThongBao.setForeground(new java.awt.Color(255, 51, 51));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taokh 105x30.png"))); // NOI18N
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setPreferredSize(new java.awt.Dimension(105, 30));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        maNVtxt.setForeground(new java.awt.Color(240, 240, 240));
        maNVtxt.setText("jLabel10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(maPXtext, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(jLabel3))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(NgayLaptext, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(ThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(maKHtext, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(MaNVtext, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(139, 139, 139)
                                .addComponent(maNVtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(mapxj))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(MaNVtext, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(maPXtext, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(maNVtxt)))
                .addGap(18, 18, 18)
                .addComponent(mapxj)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(maKHtext)
                                .addGap(35, 35, 35))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NgayLaptext, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ThongBao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taohd 70x23.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(70, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bangPX.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã PX", "Ngày Mua", "Tên NV", "Mã - Tên KH"
            }
        ));
        bangPX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangPXMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bangPX);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi Tiết Phiếu Xuất"));

        jLabel6.setText("Mã TB");

        jLabel7.setText("Đơn Giá :");

        jLabel8.setText("Số Lượng:");

        donGiatext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donGiatextActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách Chi Tiết Phiếu Xuất"));

        bangCtPX.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã - Tên TB", "Đơn Giá", "Số Lương"
            }
        ));
        bangCtPX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangCtPXMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(bangCtPX);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/them bt 50x50.png"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xoa bt 50x50.png"))); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        maTBtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maTBtextActionPerformed(evt);
            }
        });
        maTBtext.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                maTBtextPropertyChange(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save bt 50x50.png"))); // NOI18N
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        matbangian.setForeground(new java.awt.Color(240, 240, 240));
        matbangian.setText("........");

        soluongcu.setForeground(new java.awt.Color(240, 240, 240));

        maKHtxt.setForeground(new java.awt.Color(240, 240, 240));
        maKHtxt.setText("jLabel10");

        maTBx.setForeground(new java.awt.Color(240, 240, 240));
        maTBx.setText("jLabel11");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(maKHtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matbangian, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(soluongcu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(31, 31, 31))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maTBx, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(donGiatext)
                                .addComponent(soLuongtext)
                                .addComponent(maTBtext, 0, 143, Short.MAX_VALUE)))))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbhinh, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maTBtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(donGiatext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soLuongtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(matbangian)
                                    .addComponent(soluongcu)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maKHtxt)
                                    .addComponent(maTBx))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbhinh, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel9.setText("Danh Sách Phiếu Xuất :");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset 70x23.png"))); // NOI18N
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setPreferredSize(new java.awt.Dimension(70, 23));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update 70x23.png"))); // NOI18N
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setPreferredSize(new java.awt.Dimension(70, 23));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jbtThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thanhtoan_70x23.png"))); // NOI18N
        jbtThanhToan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThanhToanActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inhd_70x23.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if(PX.timTinhTrang(maPXtext.getText()).equals("true"))
        {
            JOptionPane.showMessageDialog(this, "Hóa đơn đã thanh toán không thể chỉnh sửa");
        }
        else
        {
            
            if(((mapxj.getText().equals("") || mapxj.getText() == null) || matbangian.getText().equals("")) || matbangian.getText()==null  )   
            {
                 JOptionPane.showMessageDialog(this,"Chọn đối Tượng muốn thao tác !!");
            }
            else
            {
                ThongBao.setText(ctPX.xoaCT(mapxj.getText(), maTBx.getText()));
                ArrayList<ThietBi> listTB = TB.getArrayList();
                for(int i= 0;i<listTB.size();i++)
                {
                    int soLuong = Integer.parseInt(soLuongtext.getText());
                    if(maTBx.getText().equals(listTB.get(i).getMaTB()))
                    {
                        int sodu = soLuong +listTB.get(i).getSoLuong();
                        ThietBi tb = new ThietBi(maTBx.getText(),sodu);
                        ThongBao.setText(TB.sua(tb));
                    }
                }
            } 
            hienThiTableCT(mapxj.getText());
            matbangian.setText("");
            soluongcu.setText("");
        }
    
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void maKHtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maKHtextActionPerformed
        ArrayList<KhachHang> list = KH.getArrayList();
        for(int i=0; i<list.size();i++)
        {
            String maKH = (String) maKHtext.getSelectedItem();
            String maKHcut =maKH.substring(0,maKH.indexOf("-"));
            if(maKHcut.equals(list.get(i).getMaKH()))
            {
             maKHtxt.setText(list.get(i).getMaKH());
            }
        }
    }//GEN-LAST:event_maKHtextActionPerformed

    private void bangPXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangPXMouseClicked
        NgayLaptext.setEnabled(true);
        donGiatext.setEditable(false);
        int i=bangPX.getSelectedRow();
//        donGiatext.setEditable(true);
        ArrayList<NhanVien> list = NV.getArrayList();
        ArrayList<PhieuXuat> List = PX.getArrayList();
        ArrayList<KhachHang> listKH = KH.getArrayList();
        if(i>=0)
        {

            try {
                ThongBao.setText("");
                DefaultTableModel model = (DefaultTableModel) bangPX.getModel();
                mapxj.setText(model.getValueAt(i, 0).toString());
                maPXtext.setText(model.getValueAt(i, 0).toString());
//                System.out.println(maPXtext.getText());
                xacNhan(maPXtext.getText());
                maKHtext.setEditable(false);
                Date date1 = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(i, 1).toString());
                NgayLaptext.setDate(date1);
                MaNVtext.setText(model.getValueAt(i, 2).toString());              
                maKHtext.setSelectedItem(model.getValueAt(i, 3));
                hienThiTableCT(mapxj.getText());
                matbangian.setText("");
                soluongcu.setText("");
             
                for(int a=0;a<list.size();a++)   
                {
                if(MaNVtext.getText().equals(list.get(a).getTen()))
                    {     
                    maNVtxt.setText(list.get(a).getMaNV());
                    }    
                }                
            } catch (ParseException ex) {
                Logger.getLogger(FrameKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
    }//GEN-LAST:event_bangPXMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       PhieuXuat phieuxuat = new PhieuXuat();
        phieuxuat.setMaNV(MainJFrame.maNV);
        String maKH = (String) maKHtext.getSelectedItem();
        String maKHcut =maKH.substring(0,maKH.indexOf("-"));
        ArrayList<KhachHang> list = KH.getArrayList();
        for(int i = 0 ;i < list.size();i++)
        {
            if(maKHcut.equals(list.get(i).getMaKH()))
            {               
                phieuxuat.setMaKH(list.get(i).getMaKH());
            }
        }
        Date ngayNhap  = new Date();
        phieuxuat.setNgayMua(ngayNhap);
        ThongBao.setText(PX.addPX(phieuxuat));
        ArrayList<PhieuXuat> list_px = PX.getArrayList();
        mapxj.setText(list_px.get(list_px.size()-1).getMaPX());
        hienThiTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if(PX.timTinhTrang(maPXtext.getText()).equals("true"))
        {
            JOptionPane.showMessageDialog(this, "Hóa đơn đã thanh toán không thể chỉnh sửa");
        }
        else
        {
            CtPhieuXuat ctpx = new CtPhieuXuat();
            ArrayList<ThietBi> listTB = TB.getArrayList();
            ArrayList<CtPhieuXuat> ListCT = ctPX.getArrayList();
            if(mapxj.getText().equals("") || mapxj.getText()==null )   
            {
             JOptionPane.showMessageDialog(this,"Chon PX muốn thao tác !!");
            }
            else
            {
               int flag=-1;       
               for (int i=0; i<ListCT.size();i++)
               {
                   if(maPXtext.getText().equals(ListCT.get(i).getMaPX()) && maTBx.getText().equals(ListCT.get(i).getMaTB().substring(0,ListCT.get(i).getMaTB().indexOf("-") )))
                   {
                       flag=i;
                   }
               }

               for (int i=0; i<listTB.size();i++)
               {
                   try
                   {
                       int soLuong = Integer.parseInt(soLuongtext.getText());
                       int giaBan = Integer.parseInt(donGiatext.getText());
                       if(soLuong <= 0 )  
                       {
                           ThongBao.setText("Số Lượng Phải Lớn hơn 0!!");
                       }
                       else if(soLuong <= listTB.get(i).getSoLuong() && maTBx.getText().equals(listTB.get(i).getMaTB()) )  
                       {
                           if(flag==-1) 
                           {
                               CtPhieuXuat ct = new CtPhieuXuat();
                               ct.setMaPX(mapxj.getText());          
                               ct.setMaTB( maTBx.getText());
                               ct.setSoLuong(soLuong);
                               ct.setDonGia(Integer.parseInt(donGiatext.getText()));
                               ThongBao.setText(ctPX.addCtPX(ct));
                               int sodu = listTB.get(i).getSoLuong() - soLuong;
                               ThietBi tb = new ThietBi(maTBx.getText(),sodu);
                               ThongBao.setText(TB.sua(tb));
                               hienThiTableCT(mapxj.getText());
                               break;
                           }
                           else
                           {
                               CtPhieuXuat  ct = new CtPhieuXuat(mapxj.getText(),maTBx.getText(),soLuong+ListCT.get(flag).getSoLuong(),Integer.parseInt(donGiatext.getText()));
                               ThongBao.setText(ctPX.suaCT(ct));
                               int sodu = listTB.get(i).getSoLuong() - soLuong;
                               ThietBi tb = new ThietBi(maTBx.getText(),sodu);
                               ThongBao.setText(TB.sua(tb)); 
                               hienThiTableCT(mapxj.getText());break;
                           } 
                       }
                       else
                       {
                           ThongBao.setText("Kho không đủ hàng!!");
                       }

                   }

                   catch(NumberFormatException ex)
                   {
                           JOptionPane.showMessageDialog(this,"Giá và số lượng phải là 1 số");break;
                   }
               }
            }
        }
        
         
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       try
        {
            hienThiTable();       
            ArrayList<KhachHang> list = KH.getArrayList();
            
                if(maKHtext.getItemCount() < list.size())
                {maKHtext.addItem(list.get(list.size()-1).getMaKH()+"-"+list.get(list.size()-1).getTen());}
               maKHtext.setSelectedIndex(0);
               mapxj.setText("");
             ThongBao.setText("");
         }
         catch(NullPointerException ex)
                {
                  ThongBao.setText("..");
                }

      
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(PX.timTinhTrang(maPXtext.getText()).equals("true"))
        {
            JOptionPane.showMessageDialog(this, "Hóa đơn đã thanh toán không thể chỉnh sửa");
        }
        else
        {
            try
            {
                if(maPXtext.getText().equals("") || maPXtext.getText()==null )
                {
                    JOptionPane.showMessageDialog(this,"Chọn đối Tượng muốn thao tác !!");
                }
                else   
                {
                    PhieuXuat px = new PhieuXuat(maPXtext.getText(),maNVtxt.getText().toString(),maKHtxt.getText(),NgayLaptext.getDate());
                    ThongBao.setText(PX.sua(px));
                    hienThiTable();
                }
            }
            catch(NullPointerException ex)
            {
                ThongBao.setText("..");
            }
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void bangCtPXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangCtPXMouseClicked
        ArrayList<ThietBi> listTB = TB.getArrayList();
        ArrayList<CtPhieuXuat> ListCT = ctPX.getArrayList();
        int i=bangCtPX.getSelectedRow();
        donGiatext.setEditable(false);
        if(i>=0)
        {
               DefaultTableModel model = (DefaultTableModel) bangCtPX.getModel();
                soluongcu.setText(model.getValueAt(i, 2).toString());
                
               
                donGiatext.setText(model.getValueAt(i, 1).toString());              
                soLuongtext.setText(model.getValueAt(i, 2).toString());
                String maTBcut =model.getValueAt(i, 0).toString().substring(0,model.getValueAt(i, 0).toString().indexOf("-"));
                for(int j=0;j<listTB.size();j++)
                {
                    if(maTBcut.equals(listTB.get(j).getMaTB()))
                    {
                       maTBtext.setSelectedItem(model.getValueAt(i, 0).toString());
                       matbangian.setText(listTB.get(j).getMaTB());
                    }
                    
                }
               
 
        }
    }//GEN-LAST:event_bangCtPXMouseClicked

    private void maTBtextPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_maTBtextPropertyChange

    }//GEN-LAST:event_maTBtextPropertyChange

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       themKH them = new themKH();
       them.setVisible(true);
       them.setLocationRelativeTo(null);
          
            
       
    }//GEN-LAST:event_jButton8ActionPerformed

    private void maTBtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maTBtextActionPerformed
        
         ArrayList<ThietBi> listTB = TB.getArrayList();     
      
         
         for(int i=0 ; i<listTB.size();i++)
        {
            String maTB = (String) maTBtext.getSelectedItem();
            String maTBcut =maTB.substring(0,maTB.indexOf("-"));
            
             if(maTBcut.equals(listTB.get(i).getMaTB()))
             {
               donGiatext.setText(Integer.toString(listTB.get(i).getGiaThanh()));
                
               
               jlbhinh.setIcon(new ImageIcon(getClass().getResource("/" + listTB.get(i).getHinh())));
               maTBx.setText(listTB.get(i).getMaTB());
             }
        }           
    }//GEN-LAST:event_maTBtextActionPerformed

    private void MaNVtextPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_MaNVtextPropertyChange
      ArrayList<NhanVien> list = NV.getArrayList();
      for(int i=0;i<list.size();i++)   
      {
          if(MaNVtext.getText().equals(list.get(i).getMaNV()))
          {
              maNVtxt.setText(MaNVtext.getText());
          }    
      }
    }//GEN-LAST:event_MaNVtextPropertyChange

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(PX.timTinhTrang(maPXtext.getText()).equals("true"))
        {
            JOptionPane.showMessageDialog(this, "Hóa đơn đã thanh toán không thể chỉnh sửa");
        }
        else
        {
            ArrayList<ThietBi> listTB = TB.getArrayList();
            ArrayList<CtPhieuXuat> ListCT = ctPX.getArrayList();

           if(matbangian.getText().equals("") || matbangian.getText()==null )   
            {
                JOptionPane.showMessageDialog(this,"Chon đối tượng muốn thao tác !!");
            }
            else
            {
                int temp=0;
                for(int i= 0;i<listTB.size();i++)
                {          
                    if(maTBx.getText().equals(listTB.get(i).getMaTB()))
                    {

                        temp=i;
                    }
                }
                for(int i= 0;i<listTB.size();i++)
                {
                    int socu = Integer.parseInt(soluongcu.getText());
                    int somoi = Integer.parseInt(soLuongtext.getText());
                    int flag=0;
                    if(matbangian.getText().equals(listTB.get(i).getMaTB()))
                    {


                        if(somoi <= 0)
                        {
                            ThongBao.setText("Số Lượng Phải Lớn hơn 0!!");

                        }
                        else if(somoi>0 )
                        { 
                            if(!matbangian.getText().equals(maTBx.getText()))
                            { 
                                if(somoi > listTB.get(temp).getSoLuong())
                                     {
                                    ThongBao.setText("Kho không đủ hàng!!"); break;
                                     }  
                               ThongBao.setText(ctPX.xoaCT(mapxj.getText(), matbangian.getText()));
                               int sodu = socu +listTB.get(i).getSoLuong();
                               ThietBi tb = new ThietBi(matbangian.getText().toString(),sodu);
                               ThongBao.setText(TB.sua(tb)); 
                            }
                            else if(matbangian.getText().equals(maTBx.getText()))
                            {
                                if(somoi > listTB.get(i).getSoLuong()+socu)
                                {
                                    ThongBao.setText("Kho không đủ hàng!!"); break;
                                }   
                            int sodu = socu +listTB.get(i).getSoLuong();
                            ThietBi tb = new ThietBi(matbangian.getText().toString(),sodu);
                            ThongBao.setText(TB.sua(tb));  
                            }
                        }              
                    }
                }

                CtPhieuXuat ctpx = new CtPhieuXuat();

                int flag=-1;
                for (int i=0; i<ListCT.size();i++)
                {
                    if(maPXtext.getText().equals(ListCT.get(i).getMaPX()) && maTBx.getText().equals(ListCT.get(i).getMaTB().substring(0,ListCT.get(i).getMaTB().indexOf("-"))))
                    {
                       flag=i;
                    }
                }

                     for (int i=0; i<listTB.size();i++)
                    {
                        try
                        {
                            int socu = Integer.parseInt(soluongcu.getText());
                            int soLuong = Integer.parseInt(soLuongtext.getText());
                            int giaBan = Integer.parseInt(donGiatext.getText());
                            if(soLuong <= 0 )  
                            {
                                ThongBao.setText("Số Lượng Phải Lớn hơn 0!!");
                            }
                            else if(soLuong>0 && maTBx.getText().equals(listTB.get(i).getMaTB()) )  
                            {
                                if(flag==-1) 
                                {

                                    if(soLuong>listTB.get(i).getSoLuong())
                                    {
                                        ThongBao.setText("Kho không đủ hàng!!");break;
                                    }
                                    CtPhieuXuat ct = new CtPhieuXuat();
                                    ct.setMaPX(mapxj.getText());          
                                    ct.setMaTB( maTBx.getText());
                                    ct.setSoLuong(soLuong);
                                    ct.setDonGia(Integer.parseInt(donGiatext.getText()));
                                    ThongBao.setText(ctPX.addCtPX(ct));
                                    int sodu = listTB.get(i).getSoLuong() - soLuong;
                                    ThietBi tb = new ThietBi(maTBx.getText(),sodu);
                                    ThongBao.setText(TB.sua(tb)); break;
                                }
                                else
                                {
                                    if( !matbangian.getText().equals(maTBx.getText()))
                                    {
                                        if(soLuong>listTB.get(i).getSoLuong())
                                        {
                                            ThongBao.setText("Kho không đủ hàng!!");break;
                                        }
                                        CtPhieuXuat  ct = new CtPhieuXuat(mapxj.getText(),maTBx.getText(),soLuong+ListCT.get(flag).getSoLuong(),Integer.parseInt(donGiatext.getText()));
                                        ThongBao.setText(ctPX.suaCT(ct));
                                        int sodu = listTB.get(i).getSoLuong()- soLuong;
                                        ThietBi tb = new ThietBi(maTBx.getText(),sodu);
                                        ThongBao.setText(TB.sua(tb)); break;

                                    }
                                    else if(matbangian.getText().equals(maTBx.getText()))
                                    {

                                        if(soLuong>listTB.get(i).getSoLuong()+socu)
                                        {
                                            ThongBao.setText("Kho không đủ hàng!!");break;
                                        }
                                        CtPhieuXuat  ct = new CtPhieuXuat(mapxj.getText(),maTBx.getText(),soLuong,Integer.parseInt(donGiatext.getText()));
                                        ThongBao.setText(ctPX.suaCT(ct));
                                        int sodu = listTB.get(i).getSoLuong()- soLuong+socu;
                                        ThietBi tb = new ThietBi(maTBx.getText(),sodu);
                                        ThongBao.setText(TB.sua(tb)); break;
                                    }
                                } 
                            }


                       }

                        catch(NumberFormatException ex)
                        {
                            JOptionPane.showMessageDialog(this,"Giá và số lượng phải là 1 số");break;
                        }
                    }    

            }
            hienThiTableCT(mapxj.getText());
            matbangian.setText("");
            soluongcu.setText("");
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void donGiatextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donGiatextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donGiatextActionPerformed

    private void jbtThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThanhToanActionPerformed
        if(PX.countDong(maPXtext.getText())==0)
        {
            JOptionPane.showMessageDialog(this, "Không có thiết bị để thanh toán");
        }
        else
        {
            if(PX.suaTinhTrang(maPXtext.getText()).equals("Thanh toán hóa đơn thành công"))
            {
                JOptionPane.showMessageDialog(this, PX.suaTinhTrang(maPXtext.getText())); 
                jbtThanhToan.setEnabled(false);
            }
        }
        
    }//GEN-LAST:event_jbtThanhToanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(PX.timTinhTrang(maPXtext.getText()).equals("true"))
        {
            PX.in(mapxj.getText());
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Hóa đơn chưa thanh toán không in hóa đơn");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

     
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MaNVtext;
    private com.toedter.calendar.JDateChooser NgayLaptext;
    private javax.swing.JLabel ThongBao;
    private javax.swing.JTable bangCtPX;
    private javax.swing.JTable bangPX;
    private javax.swing.JTextField donGiatext;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtThanhToan;
    private javax.swing.JLabel jlbhinh;
    private javax.swing.JComboBox<String> maKHtext;
    private javax.swing.JLabel maKHtxt;
    private javax.swing.JLabel maNVtxt;
    private javax.swing.JLabel maPXtext;
    private javax.swing.JComboBox<String> maTBtext;
    private javax.swing.JLabel maTBx;
    private javax.swing.JLabel mapxj;
    private javax.swing.JLabel matbangian;
    private javax.swing.JTextField soLuongtext;
    private javax.swing.JLabel soluongcu;
    // End of variables declaration//GEN-END:variables
}
