/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_TaiKhoan;
import DTO.TaiKhoan;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class FrameAccount extends javax.swing.JPanel {

    BLL_TaiKhoan tk = new BLL_TaiKhoan();
    /**
     * Creates new form FrameAccount
     */
    public FrameAccount() {
        
        initComponents();
        hienThiTable();
        
    }

    public void hienThiTable()
    {
        
        DefaultTableModel model = (DefaultTableModel) jtbTK.getModel();

        
        ArrayList<TaiKhoan> list = new ArrayList<TaiKhoan>();
        list = tk.getArrayList();
        
        model.setRowCount(0);
        for(int i = 0 ; i < list.size();i++)
        {
            
//            System.out.println(list.get(i).isTinhTrang());
            model.addRow(new Object[]{list.get(i).getMaTK(),list.get(i).getMaNV(),list.get(i).getUsername(),list.get(i).getPassword(),list.get(i).getQuyen(),list.get(i).isTinhTrang()} );
        }
        
    }
    public void hienThiTable(ArrayList<TaiKhoan> list)
    {
        
        DefaultTableModel model = (DefaultTableModel) jtbTK.getModel();

        
        
        model.setRowCount(0);
        for(int i = 0 ; i < list.size();i++)
        {
            
//            System.out.println(list.get(i).isTinhTrang());
            model.addRow(new Object[]{list.get(i).getMaTK(),list.get(i).getMaNV(),list.get(i).getUsername(),list.get(i).getPassword(),list.get(i).getQuyen(),list.get(i).isTinhTrang()} );
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbTK = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jrbmaTK = new javax.swing.JRadioButton();
        jrbUser = new javax.swing.JRadioButton();
        jrbMaNV = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(850, 600));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Quản lý tài khoản");

        jtbTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã TK", "Mã NV", "Username", "Password", "Quyền", "Tình Trạng"
            }
        ));
        jtbTK.setRowHeight(30);
        jtbTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbTKMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbTK);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh bt 50x50.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Tìm Kiếm");

        txtTimKiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTimKiemCaretUpdate(evt);
            }
        });

        buttonGroup1.add(jrbmaTK);
        jrbmaTK.setSelected(true);
        jrbmaTK.setText("Mã TK");

        buttonGroup1.add(jrbUser);
        jrbUser.setText("Username");

        buttonGroup1.add(jrbMaNV);
        jrbMaNV.setText("Mã NV");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrbmaTK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrbMaNV))
                            .addComponent(txtTimKiem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224)))
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbmaTK)
                    .addComponent(jrbUser)
                    .addComponent(jrbMaNV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtbTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbTKMouseClicked
        // TODO add your handling code here:
        int i=jtbTK.getSelectedRow();
        FrameThongTinAccount f = new FrameThongTinAccount();
//        System.out.println(evt.getClickCount());
        if(i>=0)
        {
           DefaultTableModel model = (DefaultTableModel) jtbTK.getModel();
           f.txtmaTK.setText(model.getValueAt(i, 0).toString());
           f.txtmaTK.setEditable(false);
           f.txtmaNV.setText(model.getValueAt(i, 1).toString());
           f.txtmaNV.setEditable(false);
           f.txtTK.setText(model.getValueAt(i, 2).toString());
           f.txtMK.setText(model.getValueAt(i, 3).toString());
           String quyen = model.getValueAt(i, 4).toString();
           f.quyen.setSelectedItem(quyen);
           if(model.getValueAt(i, 5).toString().equals("true")) f.mo.setSelected(true);
           else f.khoa.setSelected(true);
           f.setVisible(true);
           f.setLocationRelativeTo(null);
           f.setResizable(false);
           
        }

    }//GEN-LAST:event_jtbTKMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        hienThiTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTimKiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTimKiemCaretUpdate
        // TODO add your handling code here:
        if(jrbMaNV.isSelected())
        {
            hienThiTable(tk.timKiemTheoMaNV(txtTimKiem.getText()));
        }
        else if(jrbUser.isSelected())
        {
            hienThiTable(tk.timKiemTheoTen(txtTimKiem.getText()));
        }
        else    hienThiTable(tk.timKiemTheoMaTK(txtTimKiem.getText()));
                
    }//GEN-LAST:event_txtTimKiemCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrbMaNV;
    private javax.swing.JRadioButton jrbUser;
    private javax.swing.JRadioButton jrbmaTK;
    protected javax.swing.JTable jtbTK;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
